compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
  eslint-config-next@*:
    dependencies:
      next: "*"
  sass-loader@*:
    dependencies:
      node-sass: "*"
  sst-aws-cdk@*:
    dependencies:
      "@aws-cdk/cx-api": "*"
      "aws-sdk": "*"
      "@aws-cdk/cloudformation-diff": "*"
      "cdk-assets": "*"
      "@aws-cdk/cloud-assembly-schema": "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
