compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
  eslint-config-next@*:
    dependencies:
      next: "*"
  sass-loader@*:
    dependencies:
      node-sass: "*"
  "sst@*":
    peerDependencies:
      "@aws-sdk/types": "*"
  "sst-aws-cdk@*":
    peerDependencies:
      "@aws-cdk/cx-api": "*"
      "@aws-cdk/cloud-assembly-schema": "*"
      "@aws-cdk/cloudformation-diff": "*"
      "aws-sdk": "*"
    dependencies:
      "fs-extra": "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
