name: Test workflow
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      test:
        description: 'Run tests'
        required: true
        default: 'true'
      deploy:
        description: 'Deploy project'
        required: true
        default: 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        # 자동화 테스트 목적
      - name: Install dependencies
        uses: actions/setup-node@v6
        with:
          node-version: '20'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Test coverage
        run: yarn test
  deploy:
    needs: test # test job이 성공해야 deploy job이 실행된다 -> sequential, needs 키워드는 이전 job의 결과를 다음 job에 전달할 수 있다. Needs가 여러개면 [lint, test] 배열로 표시
    runs-on: ubuntu-latest # 매우중요: 각각의 jobs는 실행기(runner)를 갖는다
    needs: test
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build project
        run: yarn wesave:build
      - name: Deploy project
        run: yarn wesave:deploy
