name: Test workflow
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      test:
        description: 'Run tests'
        required: true
        default: 'true'
      deploy:
        description: 'Deploy project'
        required: true
        default: 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        # 자동화 테스트 목적
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test
  deploy:
    runs-on: ubuntu-latest # 매우중요: 각각의 jobs는 실행기(runner)를 갖는다
    needs: test
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build project
        run: pnpm wesave:build
      - name: Deploy project
        run: pnpm wesave:deploy
